# The TCP port on which the lobby will listen.
# Ensure that clients configure this port in their NETWORK_LOBBYPORT 
# setting within both Settings.cfg and GameServer.cfg.

Port = 7066

# The full or relative path to a text file on which the logs will be appended

LogPath = "./log.txt"

# Only messages with severity equal or higher than this value will be logged
# Available values are: Trace, Info, Warning, Error

LogLevel = "Info"

# A message that will appear in a popoup the first time a client joins the lobby after starting the game.

MessageOfTheDay = '''
Welcome player,
thanks for playing with us!
'''

# A message that will appear in the chat when the client joins a channel
# If you're hosting a public lobby, you're kindly asked to 
# keep at least a link to the original project
# Thank you <3

ChannelChatMessage = '''
Unofficial LobbyServer reimplementation by \cFF00FFFFKryotek
Source: \cFFAA55FFhttps://github.com/kryotek777/Sacred-Gold-LobbyServer
'''

# How many messages will be stored for the chat history
# Use 0 to disable chat history

ChatHistoryLimit = 20

# Fake servers that will be sent in the server list to act as separators.
# Servers are always ordered alphabetically by the client,
# so try to be clever with your names to preserve ordering!

ServerSeparators = [ "## Vanilla ##", "## Modded ##" ]

# A Regular Expression defining what usernames are allowed
# The default one is '^[\w-]+$' and allows letters, numbers, underscores (_), dashes (-)
AllowedUsernameRegex = '^[\w-]+$'

# Wether to store persistent data such as accounts, profile info, etc.
# If disabled, AllowAnonymousLogin will always be true
StorePersistentData = true

# The path of the file that will contain the account data for the clients
DatabasePath = "./Data/database.sqlite"

# Path of the folder that will contain the savegames for each registered user
# Every user gets a subfolder named after its internal ID and contains the .pax files for each save
SavesPath = "./Data/Saves/"

# The path of the templates that will be used when creating new charactrs in Closed Net
TemplatePath = "./Data/Templates/"

# Allow unregistered users to log in with any username
AllowAnonymousLogin = true

# Skip security checks made on packets. This allows any type of client to send any type of packets. 
# Useful with misbehaving mods
SkipSecurityChecks = false

# Collect performance statistics
CollectStatistics = true

# Enable the WebApi server
# WARNING: This is not intended to be public, DO NOT EXPOSE THE WEBAPI PORT TO THE INTERNET!
# it is meant for local control panels or website backends ONLY
EnableWebApi = false

# Enable the Swagger UI for the WebApi server
# This contains all the endpoints present in the server, you can find it at /swagger
EnableSwagger = false

# The URL on which the WebApi server will listen
WebApiUrl = "http://localhost:5000"

# The following is the channel list that's visible in closednet
# WARNING: Ensure there's always a channel with ID=6 with no flags, that's dedicated for OpenNet and hardcoded in the game!

# Valid value for the "Flags" field are: 
# - None: Open Net server with no requirements
# - Official: Visible in Closed Net, this is required
# - Noob: Player must be below level 10
# - Bronze: Bronze difficulty
# - Silver: Silver difficulty
# - Gold: Gold difficulty
# - Platinum: Platinum difficulty
# - Niobium: Niobium difficulty
# - Cheater: Player must be over level 200
# - Hardcore: Only hardcore characters!
# - Clan: Only clan members (not supported)
# - Special: Only special members (not supported)
# - VIP: Only VIP members (not supported)
# - Private: Private/Custom games

# WARNING: This first channel should not be changed unless you know what you are doing!
[[Channels]]
Name = "Open Net"
Flags = "None"
Id = 6

# You can change and add these as you please, but please skip channel 6!
[[Channels]]
Name = "Anyone"
Flags = "ClosedNet"
Id = 1

[[Channels]]
Name = "Hardcore only!"
Flags = "ClosedNet, Hardcore"
Id = 2

# Here you can ban people by their ip address
# Bans can be of three types
# Full: The connection is dropped instantly without even attemping to figure out the client's type.
# use this to ban for security reasons
# ClientOnly: They cannot play the game, but can still host servers.
# use this for cheaters and general morons
# ServerOnly: They can play the game, but cannot host servers.
# use this for players with unstable connections that insinst on hosting their server

# It is advisable to use "Full" as the ban type when dealing with dangerous clients 
# while ClientOnly and ServerOnly are advised for 'soft' bans for people who just misbehave

[[Bans]]
Ip = "169.254.0.0"
BanType = "Full"
Reason = "Attempted exploits" # Note: reason isn't shown for Full bans

[[Bans]]
Ip = "169.254.0.1"
BanType = "ClientOnly"
Reason = "Cheated characters"

[[Bans]]
Ip = "169.254.0.2"
BanType = "ServerOnly"
Reason = "Unstable servers that always crash"