using Lobby.Types;
using Lobby.Types.Messages;
using Lobby.Types.Messages.Data;

public record struct PacketSecurityData(Type MessageType, Type? MessageTypeRaw, int Length, uint SecurityKey, bool DynamicSize, bool FromClient, bool FromServer, bool FromUnknown)
{
    public static PacketSecurityData Get(SacredMsgType Type)
    {
        return PacketDictionary[Type];
    }

    private static Dictionary<SacredMsgType, PacketSecurityData> PacketDictionary = new Dictionary<SacredMsgType, PacketSecurityData> {
        { SacredMsgType.ClientRegistrationRequest, new(MessageType: typeof(RegistrationMessage), MessageTypeRaw: typeof(RegistrationMessageData), Length: 256, SecurityKey: 0xDDCCBB01, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: true)},
        { SacredMsgType.ClientLoginRequest, new(MessageType: typeof(LoginMessage), MessageTypeRaw: typeof(LoginMessageData), Length: 176, SecurityKey: 0xDDCCBB02, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: true)},
        { SacredMsgType.PrivateInfoRequest, new(MessageType: typeof(EmptyMessage), MessageTypeRaw: null, Length: 14, SecurityKey: 0xDDCCBB03, DynamicSize: false, FromClient: true, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ReceivePrivateInfo, new(MessageType: typeof(PrivateInfoMessage), MessageTypeRaw: typeof(PrivateInfoMessageData), Length: 126, SecurityKey: 0xDDCCBB04, DynamicSize: false, FromClient: true, FromServer: false, FromUnknown: false)},
        { SacredMsgType.SendPrivateInfo, new(MessageType: typeof(PrivateInfoMessage), MessageTypeRaw: typeof(PrivateInfoMessageData), Length: 126, SecurityKey: 0xDDCCBB05, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.PublicInfoRequest, new(MessageType: typeof(PublicInfoRequestMessage), MessageTypeRaw: typeof(PublicInfoRequestMessageData), Length: 18, SecurityKey: 0xDDCCBB06, DynamicSize: false, FromClient: true, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ReceivePublicInfo, new(MessageType: typeof(PublicInfoMessage), MessageTypeRaw: typeof(PublicInfoMessageData), Length: 98, SecurityKey: 0xDDCCBB07, DynamicSize: false, FromClient: true, FromServer: false, FromUnknown: false)},
        { SacredMsgType.SendPublicInfo, new(MessageType: typeof(PublicInfoMessage), MessageTypeRaw: typeof(PublicInfoMessageData), Length: 98, SecurityKey: 0xDDCCBB08, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.PublicDataRequest, new(MessageType: typeof(PublicDataRequestMessage), MessageTypeRaw: typeof(PublicDataRequestMessageData), Length: 28, SecurityKey: 0xDDCCBB09, DynamicSize: false, FromClient: true, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ReceivePublicData, new(MessageType: typeof(PublicDataMessage), MessageTypeRaw: typeof(PublicDataMessageData), Length: 131104, SecurityKey: 0xDDCCBB10, DynamicSize: true, FromClient: true, FromServer: false, FromUnknown: false)},
        { SacredMsgType.SendPublicData, new(MessageType: typeof(PublicDataMessage), MessageTypeRaw: typeof(PublicDataMessageData), Length: 131104, SecurityKey: 0xDDCCBB11, DynamicSize: true, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ServerLoginRequest, new(MessageType: typeof(ServerInfoMessage), MessageTypeRaw: typeof(ServerInfoMessageData), Length: 130, SecurityKey: 0xDDCCBB12, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: true)},
        { SacredMsgType.ServerChangePublicInfo, new(MessageType: typeof(ServerInfoMessage), MessageTypeRaw: typeof(ServerInfoMessageData), Length: 130, SecurityKey: 0xDDCCBB13, DynamicSize: false, FromClient: false, FromServer: true, FromUnknown: false)},
        { SacredMsgType.ServerLogout, new(MessageType: typeof(ServerInfoMessage), MessageTypeRaw: typeof(ServerInfoMessageData), Length: 130, SecurityKey: 0xDDCCBB14, DynamicSize: false, FromClient: false, FromServer: true, FromUnknown: false)},
        { SacredMsgType.LobbyResult, new(MessageType: typeof(ResultMessage), MessageTypeRaw: typeof(ResultMessageData), Length: 22, SecurityKey: 0xDDCCBB15, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ClientLoginResult, new(MessageType: typeof(LoginResultMessage), MessageTypeRaw: typeof(LoginResultMessageData), Length: 282, SecurityKey: 0xDDCCBB16, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ClientCharacterSelect, new(MessageType: typeof(SelectPublicDataSetMessage), MessageTypeRaw: typeof(SelectPublicDataSetMessageData), Length: 16, SecurityKey: 0xDDCCBB17, DynamicSize: false, FromClient: true, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ReceiveClientPublicDataFromServer, new(MessageType: typeof(PublicDataMessage), MessageTypeRaw: typeof(PublicDataMessageData), Length: 131104, SecurityKey: 0xDDCCBB18, DynamicSize: true, FromClient: false, FromServer: true, FromUnknown: false)},
        { SacredMsgType.ServerRequestsClientsPublicData, new(MessageType: typeof(PublicDataRequestMessage), MessageTypeRaw: typeof(PublicDataRequestMessageData), Length: 28, SecurityKey: 0xDDCCBB19, DynamicSize: false, FromClient: false, FromServer: true, FromUnknown: false)},
        { SacredMsgType.ServerListRequest, new(MessageType: typeof(RequestServerListMessage), MessageTypeRaw: typeof(RequestServerListMessageData), Length: 18, SecurityKey: 0xDDCCBB1A, DynamicSize: false, FromClient: true, FromServer: false, FromUnknown: false)},
        { SacredMsgType.SendServerInfo, new(MessageType: typeof(ServerInfoMessage), MessageTypeRaw: typeof(ServerInfoMessageData), Length: 130, SecurityKey: 0xDDCCBB1B, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.RemoveServer, new(MessageType: typeof(ServerInfoMessage), MessageTypeRaw: typeof(ServerInfoMessageData), Length: 130, SecurityKey: 0xDDCCBB1C, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ChannelListRequest, new(MessageType: typeof(EmptyMessage), MessageTypeRaw: null, Length: 14, SecurityKey: 0xDDCCBB1D, DynamicSize: false, FromClient: true, FromServer: false, FromUnknown: false)},
        { SacredMsgType.SendChannelList, new(MessageType: typeof(ChannelListMessage), MessageTypeRaw: typeof(ChannelListMessageData), Length: 11664, SecurityKey: 0xDDCCBB1E, DynamicSize: true, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ChannelJoinRequest, new(MessageType: typeof(JoinChannelMessage), MessageTypeRaw: typeof(JoinChannelMessageData), Length: 16, SecurityKey: 0xDDCCBB1F, DynamicSize: false, FromClient: true, FromServer: false, FromUnknown: false)},
        { SacredMsgType.UserJoinChannel, new(MessageType: typeof(JoinChannelMessage), MessageTypeRaw: typeof(JoinChannelMessageData), Length: 16, SecurityKey: 0xDDCCBB20, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ChannelLeaveRequest, new(MessageType: typeof(EmptyMessage), MessageTypeRaw: null, Length: 14, SecurityKey: 0xDDCCBB21, DynamicSize: false, FromClient: true, FromServer: false, FromUnknown: false)},
        { SacredMsgType.OtherUserJoinedChannel, new(MessageType: typeof(ChannelUserMessage), MessageTypeRaw: typeof(ChannelUserMessageData), Length: 98, SecurityKey: 0xDDCCBB22, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.OtherUserLeftChannel, new(MessageType: typeof(ChannelUserMessage), MessageTypeRaw: typeof(ChannelUserMessageData), Length: 98, SecurityKey: 0xDDCCBB23, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ReceiveChatMessage, new(MessageType: typeof(ChatMessage), MessageTypeRaw: typeof(ChatMessageData), Length: 358, SecurityKey: 0xDDCCBB24, DynamicSize: false, FromClient: true, FromServer: false, FromUnknown: false)},
        { SacredMsgType.SendChatMessage, new(MessageType: typeof(ChatMessage), MessageTypeRaw: typeof(ChatMessageData), Length: 358, SecurityKey: 0xDDCCBB25, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ReceivePrivateChatMessage, new(MessageType: typeof(ChatMessage), MessageTypeRaw: typeof(ChatMessageData), Length: 358, SecurityKey: 0xDDCCBB26, DynamicSize: false, FromClient: true, FromServer: true, FromUnknown: false)},
        { SacredMsgType.SendPrivateChatMessage, new(MessageType: typeof(ChatMessage), MessageTypeRaw: typeof(ChatMessageData), Length: 358, SecurityKey: 0xDDCCBB27, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.Kick, new(MessageType: typeof(KickMessage), MessageTypeRaw: typeof(KickMessageData), Length: 270, SecurityKey: 0xDDCCBB28, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.Alarm, new(MessageType: typeof(EmptyMessage), MessageTypeRaw: null, Length: 0, SecurityKey: 0xDDCCBB29, DynamicSize: false, FromClient: true, FromServer: false, FromUnknown: false)},
        { SacredMsgType.FindUserRequest, new(MessageType: typeof(FindUserMessage), MessageTypeRaw: typeof(FindUserMessageData), Length: 94, SecurityKey: 0xDDCCBB2A, DynamicSize: false, FromClient: true, FromServer: true, FromUnknown: false)},
        { SacredMsgType.FoundUser, new(MessageType: typeof(FriendInfoMessage), MessageTypeRaw: typeof(FriendInfoMessageData), Length: 274, SecurityKey: 0xDDCCBB2B, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ServerLoginResult, new(MessageType: typeof(ServerLoginInfoMessage), MessageTypeRaw: typeof(ServerLoginInfoMessageData), Length: 18, SecurityKey: 0xDDCCBB2C, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ClosedNetNewCharacter, new(MessageType: typeof(ClosedNetNewCharacterMessage), MessageTypeRaw: typeof(ClosedNetNewCharacterMessageData), Length: 18, SecurityKey: 0xDDCCBB2D, DynamicSize: false, FromClient: true, FromServer: false, FromUnknown: false)},
        { SacredMsgType.Reserved1, new(MessageType: typeof(EmptyMessage), MessageTypeRaw: null, Length: 0, SecurityKey: 0x0, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.Reserved2, new(MessageType: typeof(EmptyMessage), MessageTypeRaw: null, Length: 0, SecurityKey: 0x0, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.Reserved3, new(MessageType: typeof(EmptyMessage), MessageTypeRaw: null, Length: 0, SecurityKey: 0x0, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.Reserved4, new(MessageType: typeof(EmptyMessage), MessageTypeRaw: null, Length: 0, SecurityKey: 0x0, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.Reserved5, new(MessageType: typeof(EmptyMessage), MessageTypeRaw: null, Length: 0, SecurityKey: 0x0, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.UserJoinedServer, new(MessageType: typeof(UserJoinedServerMessage), MessageTypeRaw: typeof(UserJoinedServerMessageData), Length: 22, SecurityKey: 0xDDCCBB2E, DynamicSize: false, FromClient: false, FromServer: true, FromUnknown: false)},
        { SacredMsgType.UserLeftServer, new(MessageType: typeof(UserLeftServerMessage), MessageTypeRaw: typeof(UserLeftServerMessageData), Length: 18, SecurityKey: 0xDDCCBB2F, DynamicSize: false, FromClient: false, FromServer: true, FromUnknown: false)},
        { SacredMsgType.UserKickedFromServer, new(MessageType: typeof(UserKickedFromServerMessage), MessageTypeRaw: typeof(UserKickedFromServerMessageData), Length: 278, SecurityKey: 0xDDCCBB30, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ClientImportantMessage, new(MessageType: typeof(ImportantMessage), MessageTypeRaw: typeof(ImportantMessageData), Length: 275, SecurityKey: 0xDDCCBB31, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ServerImportantMessage, new(MessageType: typeof(ImportantMessage), MessageTypeRaw: typeof(ImportantMessageData), Length: 275, SecurityKey: 0xDDCCBB32, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.ServerShutdown, new(MessageType: typeof(ServerShutdownMessage), MessageTypeRaw: typeof(ServerShutdownMessageData), Length: 270, SecurityKey: 0xDDCCBB33, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.AddFriend, new(MessageType: typeof(BuddyMessage), MessageTypeRaw: typeof(BuddyMessage), Length: 22, SecurityKey: 0xDDCCBB34, DynamicSize: false, FromClient: true, FromServer: true, FromUnknown: false)},
        { SacredMsgType.RemoveFriend, new(MessageType: typeof(BuddyMessage), MessageTypeRaw: typeof(BuddyMessageData), Length: 22, SecurityKey: 0xDDCCBB35, DynamicSize: false, FromClient: true, FromServer: true, FromUnknown: false)},
        { SacredMsgType.AddedToFriends, new(MessageType: typeof(BuddyAddedNotificationMessage), MessageTypeRaw: typeof(BuddyAddedNotificationMessageData), Length: 102, SecurityKey: 0xDDCCBB36, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.UpdateFriendStatus, new(MessageType: typeof(FriendInfoMessage), MessageTypeRaw: typeof(FriendInfoMessageData), Length: 274, SecurityKey: 0xDDCCBB37, DynamicSize: false, FromClient: false, FromServer: false, FromUnknown: false)},
        { SacredMsgType.MessageOfTheDayRequest, new(MessageType: typeof(MotdRequestMessage), MessageTypeRaw: typeof(MotdRequestMessageData), Length: 144, SecurityKey: 0xDDCCBB38, DynamicSize: false, FromClient: true, FromServer: true, FromUnknown: false)},
        { SacredMsgType.SendMessageOfTheDay, new(MessageType: typeof(MotdMessage), MessageTypeRaw: typeof(MotdMessageData), Length: 131218, SecurityKey: 0xDDCCBB39, DynamicSize: true, FromClient: false, FromServer: false, FromUnknown: false)},
    };
}